# Site settings
title: Lei's blog
description: "Machine Learning, AI and others"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

