# Site settings
title:              "Lei's Blog"
email:              xxxx
description: > # this means to ignore newlines until "baseurl:"
  This is my blog to keep track of everything I learned or I'm interetsed.
baseurl:            ""
url:                "https://zergxyz.github.io"
twitter_username:   (Never!)
github_username:    Moe Master
future:             True
timezone:           US Central

# Build settings
markdown:           kramdown
gems:               [jekyll-paginate]
paginate:           15
