# Site settings
title: Lei's blog
email: 
description: "Machine Learning, AI and others"
baseurl: ""
url: ""
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

